server:
  port: 20611

database:
  driver: mysql
  source: "root:root@tcp(127.0.0.1:3306)/yusi?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 5
  max_open_conns: 10

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: "yusi-secret-key-should-be-very-long-and-secure-base64-encoded"
  access_token_expiration: 7200 # 2 hours in seconds
  refresh_token_expiration: 604800 # 7 days in seconds

ai:
  chat:
    base_url: ${CHAT_MODEL_BASEURL}
    api_key: ${CHAT_MODEL_APIKEY}
    model: ${CHAT_MODEL_NAME}
  embedding:
    base_url: ${EMBEDDING_MODEL_BASEURL}
    api_key: ${EMBEDDING_MODEL_APIKEY}
    model: ${EMBEDDING_MODEL_NAME}

milvus:
  uri: "https://in03-cf10f8f6eef3a63.serverless.aws-eu-central-1.cloud.zilliz.com"
  token: "064cde8da209e07bec713d60083a689eee36c6711b2228a271900f8f10d59ff3f9bb8b96ba9a494d6353593fe7794a17b775c125"

mcp:
  enabled: false
  server_url: "http://localhost:11611/mcp"
