server:
  port: 20611
  tomcat:
    threads:
      max: 200 # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50 # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10 # 等待队列长度

model:
  embedding:
    baseurl: ${EMBEDDING_MODEL_BASEURL}
    apikey: ${EMBEDDING_MODEL_APIKEY}
    model: ${EMBEDDING_MODEL_NAME}
  chat:
    baseurl: ${CHAT_MODEL_BASEURL}
    apikey: ${CHAT_MODEL_APIKEY}
    model: ${CHAT_MODEL_NAME}


# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    #    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    #    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/yusi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 60000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 120000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 15MB #上传文件单个大小限制
      max-request-size: 60MB #上传文件总大小限制
      enabled: true #是否开启文件上传功能，默认false
  jpa:
    show-sql: true #是否打印SQL语句，默认false
    hibernate:
      ddl-auto: update #自动更新数据库表结构，默认none，可选值none、create、create-drop、validate、update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy #数据库表和字段的命名策略，默认org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect #数据库方言，默认org.hibernate.dialect.MySQL5Dialect

#Redis 配置
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

milvus:
  mode: 2
  uri: https://in03-cf10f8f6eef3a63.serverless.aws-eu-central-1.cloud.zilliz.com
  token: 064cde8da209e07bec713d60083a689eee36c6711b2228a271900f8f10d59ff3f9bb8b96ba9a494d6353593fe7794a17b775c125
  host:
  port:
  username:
  password:

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
